### ISSUE TITLE
Popup screens

### ISSUE THREAD

**Issue by heuvelc** [JelteMX/mendix-tree-table#22]
Hi @JelteMX 

As fas as I can see in all of my testing (Mx 8.7 and later) opening a page from the TreeTable seems to ignore the setting (type, size and resizable indicator) of the page?

Whatever the settings are I do get a popup screen of 600px width, non -resizable page, either modal or normal depending on the setting in TreeTable.

Could you have a look at this?

Regards

Cees van den Heuvel

**Comment by JelteMX** [comment]
Unfortunately that seems to be a bug in the platform then, because this uses the standard [openForm](https://apidocs.mendix.com/8/client/mx.ui.html#.openForm) API. I suggest you open the page using a Microflow/Nanoflow then, instead of the Open Page action. I'll ask R&D whether or not something has changed in their APIs here.

**Comment by heuvelc** [comment]
OK, i will check in de demo project and in my own project (Mx8.10) if that will work as a workaround and keep you posted.

Regards

Cees

**Comment by heuvelc** [comment]
Opening pages using MF's works fine, the page settings are respected as you would expect.

I will work around the issue for now.

**Comment by JelteMX** [comment]
As this issue is in the platform (can't fix it in the widget) and there is a workaround, I am closing this issue
